### PR TITLE
docs(Select): add custom option label example

### PR DESCRIPTION
**Pull request by gonzavz**
Create a story book example to customize  multi value select.

### CODE REVIEW

**Comment by ajkl2533** [comment]
@gonzavz Please drop Stepper visual test change and squash commits into just one with message:
```
docs(Select): add custom option label example

**Comment by gonzavz** [comment]
> @gonzavz Please drop Stepper visual test change and squash commits into just one with message:
> 
> ```
> docs(Select): add custom option label example
> ```

Hi @ajkl2533 Yes, First I need to fix the visual-regression test, after that I'll create 1 commit for all the changes

**Comment by gonzavz** [comment]
Hi @ajkl2533 I updated the PR, can you take look

**Comment by ajkl2533** [comment]
@gonzavz please drop the Stepper visual test changes, Stepper is flaky at the moment, if your test fail just rerun

**Comment by gonzavz** [comment]
> @gonzavz please drop the Stepper visual test changes, Stepper is flaky at the moment, if your test fail just rerun
Sure

**Review by ajkl2533 — APPROVED** [review]

**Pull request merged**
